"""empty message

Revision ID: 8bcfa205ecde
Revises: 4c4230692778
Create Date: 2021-05-07 19:53:52.210321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcfa205ecde'
down_revision = '4c4230692778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('module_id', sa.Integer(), nullable=False))
    op.drop_constraint('errors_modules_id_fkey', 'errors', type_='foreignkey')
    op.create_foreign_key(None, 'errors', 'modules', ['module_id'], ['id'])
    op.drop_column('errors', 'modules_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('modules_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'errors', type_='foreignkey')
    op.create_foreign_key('errors_modules_id_fkey', 'errors', 'modules', ['modules_id'], ['id'])
    op.drop_column('errors', 'module_id')
    # ### end Alembic commands ###
