"""fix name on modules

Revision ID: bcc7c69dc66e
Revises: a952e394ae8a
Create Date: 2021-05-06 13:20:55.990888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc7c69dc66e'
down_revision = 'a952e394ae8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('mod_name', sa.String(length=40), nullable=False))
    op.drop_constraint('modules_name_key', 'modules', type_='unique')
    op.create_unique_constraint(None, 'modules', ['mod_name'])
    op.drop_column('modules', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='unique')
    op.create_unique_constraint('modules_name_key', 'modules', ['name'])
    op.drop_column('modules', 'mod_name')
    # ### end Alembic commands ###
