"""empty message

Revision ID: 115a2f19f4cb
Revises: bcc7c69dc66e
Create Date: 2021-05-06 13:24:24.603393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115a2f19f4cb'
down_revision = 'bcc7c69dc66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('name', sa.String(length=40), nullable=False))
    op.drop_constraint('modules_mod_name_key', 'modules', type_='unique')
    op.create_unique_constraint(None, 'modules', ['name'])
    op.drop_column('modules', 'mod_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('mod_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'modules', type_='unique')
    op.create_unique_constraint('modules_mod_name_key', 'modules', ['mod_name'])
    op.drop_column('modules', 'name')
    # ### end Alembic commands ###
