"""remove unique constraints for error and answer

Revision ID: 66e24f77e4ba
Revises: a92f4ec226f5
Create Date: 2021-05-15 20:20:30.179592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e24f77e4ba'
down_revision = 'a92f4ec226f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_description_key', 'answers', type_='unique')
    op.drop_constraint('errors_description_key', 'errors', type_='unique')
    op.drop_constraint('errors_title_key', 'errors', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('errors_title_key', 'errors', ['title'])
    op.create_unique_constraint('errors_description_key', 'errors', ['description'])
    op.create_unique_constraint('answers_description_key', 'answers', ['description'])
    # ### end Alembic commands ###
