"""add unread to messages

Revision ID: a92f4ec226f5
Revises: d671b27f6ff0
Create Date: 2021-05-12 21:33:44.917863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92f4ec226f5'
down_revision = 'd671b27f6ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('unread', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'unread')
    # ### end Alembic commands ###
